export const authConstant = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
};

export const userConstant = {
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
};

export const category = {
  CATEGORY_REQUEST: 'CATEGORY_REQUEST',
  CATEGORY_SUCCESS: 'CATEGORY_SUCCESS',
  CATEGORY_FAILURE: 'CATEGORY_FAILURE',
  ADD_CATEGORY_REQUEST: 'ADD_CATEGORY_REQUEST',
  ADD_CATEGORY_SUCCESS: 'ADD_CATEGORY_SUCCESS',
  ADD_CATEGORY_FAILURE: 'ADD_CATEGORY_FAILURE',
};

export const Product = {
  ADD_PRODUCT_REQUEST: 'ADD_PRODUCT_REQUEST',
  ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
  ADD_PRODUCT_FAILURE: 'ADD_PRODUCT_FAILURE',
};

export const getProduct = {
  GETALL_PRODUCT_REQUEST: '  GETALL_PRODUCT_REQUEST',
  GETALL_PRODUCT_SUCCESS: '  GETALL_PRODUCT_SUCCESS',
  GETALL_PRODUCT_FAILURE: '  GETALL_PRODUCT_FAILURE',
};

export const initialData = {
  GETALL_INITIALDATA_REQUEST: '  GETALL_INITIALDATA_REQUEST',
  GETALL_INITIALDATA_SUCCESS: '  GETALL_INITIALDATA_SUCCESS',
  GETALL_INITIALDATA_FAILURE: '  GETALL_INITIALDATA_FAILURE',
};
